name: "Checkov Job"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checkov-job:
    name: "Checkov Action"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Run Checkov"
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          output_format: "json"
          output_file_path: "checkov_results.json"
        continue-on-error: true

      - name: "Upload Checkov Results"
        uses: actions/upload-artifact@v3
        with:
          name: checkov-results
          path: checkov_results.json

      - name: "Parse Checkov Output"
        id: parse_output
        continue-on-error: true
        run: |
          # Ensure jq is installed
          sudo apt-get update && sudo apt-get install -y jq || true

          # Extract failed check count and a summary message from the Checkov output
          if [ -f checkov_results.json ]; then
            failed_count=$(jq '.results.failed_checks | length' checkov_results.json 2>/dev/null) || failed_count=0
            passed_count=$(jq '.results.passed_checks | length' checkov_results.json 2>/dev/null) || passed_count=0
            suppressed_count=$(jq '.results.suppressed_checks | length' checkov_results.json 2>/dev/null) || suppressed_count=0

            output="### Checkov Results\n\n- **Passed Checks:** $passed_count\n- **Failed Checks:** $failed_count\n- **Suppressed Checks:** $suppressed_count\n\n"

            if [ "$failed_count" -gt 0 ]; then
              output="${output}:x: Some checks failed! Please [download the full Checkov report](https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}) to see the details."
            else
              output="${output}:white_check_mark: All checks passed!"
            fi
          else
            output=":warning: Checkov results not found or Checkov failed."
          fi

          echo "::set-output name=checkov_output::$output"

      - name: "Post Checkov PR Comment"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### Checkov Results\n\n${process.env.CHECKOV_OUTPUT}\n`
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: output
            })
        env:
          CHECKOV_OUTPUT: ${{ steps.parse_output.outputs.checkov_output }}
